/**
 * Polyfills for Node.js environment to fix navigator global errors
 * This file provides browser-like globals for web libraries running in Node.js
 *
 * NOTE: These polyfills are intended for Node.js/SSR environments only.
 * They provide browser-like globals when window is not available.
 * Node.js-specific imports are avoided to prevent build issues.
 */

// Only apply polyfills in Node.js/SSR environment (when window is undefined)
if (typeof window === 'undefined' && typeof globalThis !== 'undefined') {
  // Ensure navigator is properly defined for web libraries
  if ((globalThis as Record<string, unknown>).navigator === undefined) {
    (globalThis as Record<string, unknown>).navigator = {
      userAgent: 'Node.js',
      platform: 'Node.js',
      language: 'en-US',
      languages: ['en-US', 'en'],
      onLine: true,
      cookieEnabled: false,
      product: 'Node.js',
      productSub: 'unknown',
      vendor: 'Node.js',
      vendorSub: '',
      appName: 'Node.js',
      appCodeName: 'Node.js',
      appVersion: '0.0.0',
      hardwareConcurrency:
        (navigator as Navigator | undefined)?.hardwareConcurrency || 1,
      maxTouchPoints: 0,
      clipboard: {
        readText: async () => '',
        writeText: async () => {},
        read: async () => Promise.reject(new Error('Not supported in Node.js')),
        write: async () =>
          Promise.reject(new Error('Not supported in Node.js')),
        addEventListener: () => {},
        removeEventListener: () => {},
        dispatchEvent: () => true,
      },
      permissions: {
        query: async () => ({
          state: 'denied' as PermissionState,
          name: 'clipboard-read',
          onchange: null,
          addEventListener: () => {},
          removeEventListener: () => {},
          dispatchEvent: () => true,
        }),
      },
      geolocation: {
        getCurrentPosition: (
          _success: PositionCallback,
          error?: PositionErrorCallback,
          _options?: PositionOptions
        ) => {
          if (error) {
            const geoError: GeolocationPositionError = {
              code: 2,
              message: 'Not supported in Node.js',
              PERMISSION_DENIED: 1,
              POSITION_UNAVAILABLE: 2,
              TIMEOUT: 3,
            };
            error(geoError);
          }
        },
        watchPosition: (
          _success: PositionCallback,
          error?: PositionErrorCallback,
          _options?: PositionOptions
        ): number => {
          if (error) {
            const geoError: GeolocationPositionError = {
              code: 2,
              message: 'Not supported in Node.js',
              PERMISSION_DENIED: 1,
              POSITION_UNAVAILABLE: 2,
              TIMEOUT: 3,
            };
            error(geoError);
          }
          return 0;
        },
        clearWatch: (_id: number) => {},
      },
      mediaDevices: {
        getUserMedia: async () =>
          Promise.reject(new Error('Not supported in Node.js')),
        enumerateDevices: async () => [],
        getDisplayMedia: async () =>
          Promise.reject(new Error('Not supported in Node.js')),
        ondevicechange: null,
        getSupportedConstraints: () => ({}),
        addEventListener: () => {},
        removeEventListener: () => {},
        dispatchEvent: () => true,
      },
      serviceWorker: {
        register: async () =>
          Promise.reject(new Error('Not supported in Node.js')),
        getRegistrations: async () => [],
        getRegistration: async () => null,
      },
      storage: {
        estimate: async () => ({ quota: 0, usage: 0 }),
        persist: async () => false,
        persisted: async () => false,
        getDirectory: async () =>
          Promise.reject(new Error('Not supported in Node.js')),
      },
    };
  }

  // Ensure window is properly defined for web libraries
  if (typeof (globalThis as { window?: Window }).window === 'undefined') {
    (globalThis as { window: typeof globalThis }).window = globalThis;
  }

  // Helper function to create a standard element stub with common properties
  const createElementStub = (overrides: Partial<HTMLElement> = {}) => ({
    addEventListener: () => {},
    removeEventListener: () => {},
    setAttribute: () => {},
    getAttribute: () => null,
    style: {},
    accessKey: '',
    accessKeyLabel: '',
    autocapitalize: '',
    autocorrect: '',
    autofocus: false,
    contentEditable: '',
    dir: '',
    draggable: false,
    hidden: false,
    innerText: '',
    innerHTML: '',
    isContentEditable: false,
    lang: '',
    offsetHeight: 0,
    offsetLeft: 0,
    offsetParent: null,
    offsetTop: 0,
    offsetWidth: 0,
    outerText: '',
    outerHTML: '',
    spellcheck: false,
    tabIndex: 0,
    title: '',
    translate: false,
    blur: () => {},
    click: () => {},
    focus: () => {},
    attachInternals: () => ({}),
    attachShadow: () => ({}),
    closest: () => null,
    getAttributeNames: () => [],
    getAttributeNode: () => null,
    getAttributeNodeNS: () => null,
    getBoundingClientRect: () => ({
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      width: 0,
      height: 0,
      x: 0,
      y: 0,
      toJSON: () => ({}),
    }),
    getClientRects: () => [],
    getElementsByClassName: () => [],
    getElementsByTagName: () => [],
    getElementsByTagNameNS: () => [],
    hasAttribute: () => false,
    hasAttributeNS: () => false,
    hasAttributes: () => false,
    hasPointerCapture: () => false,
    insertAdjacentElement: () => null,
    insertAdjacentHTML: () => {},
    insertAdjacentText: () => {},
    matches: () => false,
    releasePointerCapture: () => {},
    removeAttribute: () => {},
    removeAttributeNode: () => null,
    removeAttributeNS: () => {},
    requestFullscreen: () => Promise.resolve(),
    requestPointerLock: () => {},
    setAttributeNode: () => null,
    setAttributeNodeNS: () => null,
    setPointerCapture: () => {},
    toggleAttribute: () => false,
    webkitMatchesSelector: () => false,
    ...overrides,
  });

  // Helper function to create a CSSStyleDeclaration stub
  const createCSSStyleDeclarationStub = (): CSSStyleDeclaration =>
    ({
      accentColor: '',
      alignContent: '',
      alignItems: '',
      alignSelf: '',
      alignmentBaseline: '',
      all: '',
      animation: '',
      animationComposition: '',
      animationDelay: '',
      animationDirection: '',
      animationDuration: '',
      animationFillMode: '',
      animationIterationCount: '',
      animationName: '',
      animationPlayState: '',
      animationTimingFunction: '',
      appearance: '',
      aspectRatio: '',
      backdropFilter: '',
      backfaceVisibility: '',
      background: '',
      backgroundAttachment: '',
      backgroundBlendMode: '',
      backgroundClip: '',
      backgroundColor: '',
      backgroundImage: '',
      backgroundOrigin: '',
      backgroundPosition: '',
      backgroundPositionX: '',
      backgroundPositionY: '',
      backgroundRepeat: '',
      backgroundSize: '',
      baselineShift: '',
      baselineSource: '',
      blockSize: '',
      border: '',
      borderBlock: '',
      borderBlockColor: '',
      borderBlockEnd: '',
      borderBlockEndColor: '',
      borderBlockEndStyle: '',
      borderBlockEndWidth: '',
      borderBlockStart: '',
      borderBlockStartColor: '',
      borderBlockStartStyle: '',
      borderBlockStartWidth: '',
      borderBlockStyle: '',
      borderBlockWidth: '',
      borderBottom: '',
      borderBottomColor: '',
      borderBottomLeftRadius: '',
      borderBottomRightRadius: '',
      borderBottomStyle: '',
      borderBottomWidth: '',
      borderCollapse: '',
      borderColor: '',
      borderEndEndRadius: '',
      borderEndStartRadius: '',
      borderImage: '',
      borderImageOutset: '',
      borderImageRepeat: '',
      borderImageSlice: '',
      borderImageSource: '',
      borderImageWidth: '',
      borderInline: '',
      borderInlineColor: '',
      borderInlineEnd: '',
      borderInlineEndColor: '',
      borderInlineEndStyle: '',
      borderInlineEndWidth: '',
      borderInlineStart: '',
      borderInlineStartColor: '',
      borderInlineStartStyle: '',
      borderInlineStartWidth: '',
      borderInlineStyle: '',
      borderInlineWidth: '',
      borderLeft: '',
      borderLeftColor: '',
      borderLeftStyle: '',
      borderLeftWidth: '',
      borderRadius: '',
      borderRight: '',
      borderRightColor: '',
      borderRightStyle: '',
      borderRightWidth: '',
      borderSpacing: '',
      borderStartEndRadius: '',
      borderStartStartRadius: '',
      borderStyle: '',
      borderTop: '',
      borderTopColor: '',
      borderTopLeftRadius: '',
      borderTopRightRadius: '',
      borderTopStyle: '',
      borderTopWidth: '',
      borderWidth: '',
      bottom: '',
      boxDecorationBreak: '',
      boxShadow: '',
      boxSizing: '',
      breakAfter: '',
      breakBefore: '',
      breakInside: '',
      captionSide: '',
      caretColor: '',
      clear: '',
      clip: '',
      clipPath: '',
      clipRule: '',
      color: '',
      colorInterpolation: '',
      colorInterpolationFilters: '',
      colorScheme: '',
      columnCount: '',
      columnFill: '',
      columnGap: '',
      columnRule: '',
      columnRuleColor: '',
      columnRuleStyle: '',
      columnRuleWidth: '',
      columnSpan: '',
      columnWidth: '',
      columns: '',
      contain: '',
      containIntrinsicBlockSize: '',
      containIntrinsicHeight: '',
      containIntrinsicInlineSize: '',
      containIntrinsicSize: '',
      containIntrinsicWidth: '',
      container: '',
      containerName: '',
      containerType: '',
      content: '',
      contentVisibility: '',
      counterIncrement: '',
      counterReset: '',
      counterSet: '',
      cssFloat: '',
      cssText: '',
      cursor: '',
      cx: '',
      cy: '',
      d: '',
      direction: '',
      display: '',
      dominantBaseline: '',
      emptyCells: '',
      fill: '',
      fillOpacity: '',
      fillRule: '',
      filter: '',
      flex: '',
      flexBasis: '',
      flexDirection: '',
      flexFlow: '',
      flexGrow: '',
      flexShrink: '',
      flexWrap: '',
      float: '',
      floodColor: '',
      floodOpacity: '',
      font: '',
      fontFamily: '',
      fontFeatureSettings: '',
      fontKerning: '',
      fontOpticalSizing: '',
      fontPalette: '',
      fontSize: '',
      fontSizeAdjust: '',
      fontStretch: '',
      fontStyle: '',
      fontSynthesis: '',
      fontSynthesisSmallCaps: '',
      fontSynthesisStyle: '',
      fontSynthesisWeight: '',
      fontVariant: '',
      fontVariantAlternates: '',
      fontVariantCaps: '',
      fontVariantEastAsian: '',
      fontVariantLigatures: '',
      fontVariantNumeric: '',
      fontVariantPosition: '',
      fontVariationSettings: '',
      fontWeight: '',
      forcedColorAdjust: '',
      gap: '',
      grid: '',
      gridArea: '',
      gridAutoColumns: '',
      gridAutoFlow: '',
      gridAutoRows: '',
      gridColumn: '',
      gridColumnEnd: '',
      gridColumnGap: '',
      gridColumnStart: '',
      gridGap: '',
      gridRow: '',
      gridRowEnd: '',
      gridRowGap: '',
      gridRowStart: '',
      gridTemplate: '',
      gridTemplateAreas: '',
      gridTemplateColumns: '',
      gridTemplateRows: '',
      height: '',
      hyphenateCharacter: '',
      hyphenateLimitChars: '',
      hyphens: '',
      imageOrientation: '',
      imageRendering: '',
      inlineSize: '',
      inset: '',
      insetBlock: '',
      insetBlockEnd: '',
      insetBlockStart: '',
      insetInline: '',
      insetInlineEnd: '',
      insetInlineStart: '',
      isolation: '',
      justifyContent: '',
      justifyItems: '',
      justifySelf: '',
      left: '',
      length: 0,
      letterSpacing: '',
      lightingColor: '',
      lineBreak: '',
      lineHeight: '',
      listStyle: '',
      listStyleImage: '',
      listStylePosition: '',
      listStyleType: '',
      margin: '',
      marginBlock: '',
      marginBlockEnd: '',
      marginBlockStart: '',
      marginBottom: '',
      marginInline: '',
      marginInlineEnd: '',
      marginInlineStart: '',
      marginLeft: '',
      marginRight: '',
      marginTop: '',
      marker: '',
      markerEnd: '',
      markerMid: '',
      markerStart: '',
      mask: '',
      maskClip: '',
      maskComposite: '',
      maskImage: '',
      maskMode: '',
      maskOrigin: '',
      maskPosition: '',
      maskRepeat: '',
      maskSize: '',
      maskType: '',
      mathDepth: '',
      mathStyle: '',
      maxBlockSize: '',
      maxHeight: '',
      maxInlineSize: '',
      maxWidth: '',
      minBlockSize: '',
      minHeight: '',
      minInlineSize: '',
      minWidth: '',
      mixBlendMode: '',
      objectFit: '',
      objectPosition: '',
      offset: '',
      offsetAnchor: '',
      offsetDistance: '',
      offsetPath: '',
      offsetPosition: '',
      offsetRotate: '',
      opacity: '',
      order: '',
      orphans: '',
      outline: '',
      outlineColor: '',
      outlineOffset: '',
      outlineStyle: '',
      outlineWidth: '',
      overflow: '',
      overflowAnchor: '',
      overflowBlock: '',
      overflowClipMargin: '',
      overflowInline: '',
      overflowWrap: '',
      overflowX: '',
      overflowY: '',
      overscrollBehavior: '',
      overscrollBehaviorBlock: '',
      overscrollBehaviorInline: '',
      overscrollBehaviorX: '',
      overscrollBehaviorY: '',
      padding: '',
      paddingBlock: '',
      paddingBlockEnd: '',
      paddingBlockStart: '',
      paddingBottom: '',
      paddingInline: '',
      paddingInlineEnd: '',
      paddingInlineStart: '',
      paddingLeft: '',
      paddingRight: '',
      paddingTop: '',
      page: '',
      pageBreakAfter: '',
      pageBreakBefore: '',
      pageBreakInside: '',
      paintOrder: '',
      parentRule: null,
      perspective: '',
      perspectiveOrigin: '',
      placeContent: '',
      placeItems: '',
      placeSelf: '',
      pointerEvents: '',
      position: '',
      printColorAdjust: '',
      quotes: '',
      r: '',
      resize: '',
      right: '',
      rotate: '',
      rowGap: '',
      rubyAlign: '',
      rubyPosition: '',
      rx: '',
      ry: '',
      scale: '',
      scrollBehavior: '',
      scrollMargin: '',
      scrollMarginBlock: '',
      scrollMarginBlockEnd: '',
      scrollMarginBlockStart: '',
      scrollMarginBottom: '',
      scrollMarginInline: '',
      scrollMarginInlineEnd: '',
      scrollMarginInlineStart: '',
      scrollMarginLeft: '',
      scrollMarginRight: '',
      scrollMarginTop: '',
      scrollPadding: '',
      scrollPaddingBlock: '',
      scrollPaddingBlockEnd: '',
      scrollPaddingBlockStart: '',
      scrollPaddingBottom: '',
      scrollPaddingInline: '',
      scrollPaddingInlineEnd: '',
      scrollPaddingInlineStart: '',
      scrollPaddingLeft: '',
      scrollPaddingRight: '',
      scrollPaddingTop: '',
      scrollSnapAlign: '',
      scrollSnapStop: '',
      scrollSnapType: '',
      scrollbarColor: '',
      scrollbarGutter: '',
      scrollbarWidth: '',
      shapeImageThreshold: '',
      shapeMargin: '',
      shapeOutside: '',
      shapeRendering: '',
      stopColor: '',
      stopOpacity: '',
      stroke: '',
      strokeDasharray: '',
      strokeDashoffset: '',
      strokeLinecap: '',
      strokeLinejoin: '',
      strokeMiterlimit: '',
      strokeOpacity: '',
      strokeWidth: '',
      tabSize: '',
      tableLayout: '',
      textAlign: '',
      textAlignLast: '',
      textAnchor: '',
      textBox: '',
      textBoxEdge: '',
      textBoxTrim: '',
      textCombineUpright: '',
      textDecoration: '',
      textDecorationColor: '',
      textDecorationLine: '',
      textDecorationSkipInk: '',
      textDecorationStyle: '',
      textDecorationThickness: '',
      textEmphasis: '',
      textEmphasisColor: '',
      textEmphasisPosition: '',
      textEmphasisStyle: '',
      textIndent: '',
      textOrientation: '',
      textOverflow: '',
      textRendering: '',
      textShadow: '',
      textTransform: '',
      textUnderlineOffset: '',
      textUnderlinePosition: '',
      textWrap: '',
      textWrapMode: '',
      textWrapStyle: '',
      top: '',
      touchAction: '',
      transform: '',
      transformBox: '',
      transformOrigin: '',
      transformStyle: '',
      transition: '',
      transitionBehavior: '',
      transitionDelay: '',
      transitionDuration: '',
      transitionProperty: '',
      transitionTimingFunction: '',
      translate: '',
      unicodeBidi: '',
      userSelect: '',
      vectorEffect: '',
      verticalAlign: '',
      viewTransitionClass: '',
      viewTransitionName: '',
      visibility: '',
      webkitAlignContent: '',
      webkitAlignItems: '',
      webkitAlignSelf: '',
      webkitAnimation: '',
      webkitAnimationDelay: '',
      webkitAnimationDirection: '',
      webkitAnimationDuration: '',
      webkitAnimationFillMode: '',
      webkitAnimationIterationCount: '',
      webkitAnimationName: '',
      webkitAnimationPlayState: '',
      webkitAnimationTimingFunction: '',
      webkitAppearance: '',
      webkitBackfaceVisibility: '',
      webkitBackgroundClip: '',
      webkitBackgroundOrigin: '',
      webkitBackgroundSize: '',
      webkitBorderBottomLeftRadius: '',
      webkitBorderBottomRightRadius: '',
      webkitBorderRadius: '',
      webkitBorderTopLeftRadius: '',
      webkitBorderTopRightRadius: '',
      webkitBoxAlign: '',
      webkitBoxFlex: '',
      webkitBoxOrdinalGroup: '',
      webkitBoxOrient: '',
      webkitBoxPack: '',
      webkitBoxShadow: '',
      webkitBoxSizing: '',
      webkitFilter: '',
      webkitFlex: '',
      webkitFlexBasis: '',
      webkitFlexDirection: '',
      webkitFlexFlow: '',
      webkitFlexGrow: '',
      webkitFlexShrink: '',
      webkitFlexWrap: '',
      webkitJustifyContent: '',
      webkitLineClamp: '',
      webkitMask: '',
      webkitMaskBoxImage: '',
      webkitMaskBoxImageOutset: '',
      webkitMaskBoxImageRepeat: '',
      webkitMaskBoxImageSlice: '',
      webkitMaskBoxImageSource: '',
      webkitMaskBoxImageWidth: '',
      webkitMaskClip: '',
      webkitMaskComposite: '',
      webkitMaskImage: '',
      webkitMaskOrigin: '',
      webkitMaskPosition: '',
      webkitMaskRepeat: '',
      webkitMaskSize: '',
      webkitOrder: '',
      webkitPerspective: '',
      webkitPerspectiveOrigin: '',
      webkitTextFillColor: '',
      webkitTextSizeAdjust: '',
      webkitTextStroke: '',
      webkitTextStrokeColor: '',
      webkitTextStrokeWidth: '',
      webkitTransform: '',
      webkitTransformOrigin: '',
      webkitTransformStyle: '',
      webkitTransition: '',
      webkitTransitionDelay: '',
      webkitTransitionDuration: '',
      webkitTransitionProperty: '',
      webkitTransitionTimingFunction: '',
      webkitUserSelect: '',
      whiteSpace: '',
      whiteSpaceCollapse: '',
      widows: '',
      width: '',
      willChange: '',
      wordBreak: '',
      wordSpacing: '',
      wordWrap: '',
      writingMode: '',
      x: '',
      y: '',
      zIndex: '',
      zoom: '',
      getPropertyPriority: (_property: string): string => '',
      getPropertyValue: (_property: string): string => '',
      item: (_index: number): string => '',
      removeProperty: (_property: string): string => '',
      setProperty: (
        _property: string,
        _value: string | null,
        _priority?: string
      ): void => {},
      [Symbol.iterator]: function* (): IterableIterator<string> {},
    } as CSSStyleDeclaration);

  // Ensure document is properly defined for web libraries
  if (typeof (globalThis as { document?: Document }).document === 'undefined') {
    (globalThis as Record<string, unknown>).document = {
      createElement: () => createElementStub(),
      createTextNode: () => ({
        wholeText: '',
        splitText: () => ({}),
        nodeValue: '',
        data: '',
        length: 0,
        appendData: () => {},
        deleteData: () => {},
        insertData: () => {},
        replaceData: () => {},
        substringData: () => '',
      }),
      createDocumentFragment: () => ({
        ownerDocument: null,
        getElementById: () => null,
        textContent: '',
        baseURI: '',
        childElementCount: 0,
        children: [],
        firstElementChild: null,
        lastElementChild: null,
        nextElementSibling: null,
        previousElementSibling: null,
        querySelector: () => null,
        querySelectorAll: () => [],
        append: () => {},
        prepend: () => {},
        replaceChildren: () => {},
      }),
      querySelector: () => null,
      querySelectorAll: () => ({
        item: () => null,
        length: 0,
        [Symbol.iterator]: function* () {},
      }),
      getElementById: () => null,
      getElementsByTagName: () => ({
        item: () => null,
        namedItem: () => null,
        length: 0,
        [Symbol.iterator]: function* () {},
      }),
      getElementsByClassName: () => ({
        item: () => null,
        namedItem: () => null,
        length: 0,
        [Symbol.iterator]: function* () {},
      }),
      addEventListener: () => {},
      removeEventListener: () => {},
      body: createElementStub({
        style: createCSSStyleDeclarationStub(),
      }),
      head: createElementStub({
        style: createCSSStyleDeclarationStub(),
      }),
      location: {
        href: '',
        protocol: 'http:',
        host: '',
        hostname: '',
        port: '',
        pathname: '',
        search: '',
        hash: '',
        origin: '',
        ancestorOrigins: null,
        assign: () => {},
        reload: () => {},
        replace: () => {},
      },
      cookie: '',
      referrer: '',
      title: '',
      readyState: 'complete',
      visibilityState: 'hidden',
      hidden: true,
    };
  }

  // Ensure location is properly defined
  if (typeof (globalThis as { location?: Location }).location === 'undefined') {
    (globalThis as { location: Partial<Location> }).location = {
      href: '',
      protocol: 'http:',
      host: '',
      hostname: '',
      port: '',
      pathname: '',
      search: '',
      hash: '',
      origin: '',
      assign: () => {},
      reload: () => {},
      replace: () => {},
    };
  }

  // Note: crypto, fetch, URL, TextEncoder, and performance are built-in to modern browsers
  // and don't need polyfilling in browser environment

  // Fix console for Node.js (ensure all methods exist)
  if (typeof (globalThis as { console?: Console }).console === 'undefined') {
    const noop = () => {};
    (globalThis as { console: unknown }).console = {
      log: noop,
      warn: noop,
      error: noop,
      info: noop,
      debug: noop,
      trace: noop,
      time: noop,
      timeEnd: noop,
      timeLog: noop,
      count: noop,
      countReset: noop,
      group: noop,
      groupEnd: noop,
      groupCollapsed: noop,
      clear: noop,
      assert: noop,
      dir: noop,
      dirxml: noop,
      table: noop,
      timeStamp: noop,
      profile: noop,
      profileEnd: noop,
    };
  }
}

// Export to ensure this file is treated as a module
export {};
